## Dataset with Neural Networks

In [2]:
import pandas as pd
from torch.utils.data import Dataset, DataLoader
import torch
import torch.nn as nn

In [2]:
df = pd.read_csv("titanic_train_minmax_scaled.csv")

In [ ]:
class TitanicDataset(Dataset):
  def __init__(self, df):
    self.df = df
    self.X = torch.tensor(df.drop(columns = ['Survived']).values, dtype = torch.float32)
    # self.y = torch.tensor(df['Survived'].values, dtype = torch.float32)
    labels = torch.tensor(df["Survived"].values, dtype=torch.long)
    self.y = torch.zeros((len(labels), 2), dtype=torch.float32)
    self.y[torch.arange(len(labels)), labels] = 1.0
  
  def __len__(self):
    self.len = len(self.df)
    return self.len
  
  def __getitem__(self, index):
    return (self.X[index], self.y[index])

dataset = TitanicDataset(df)
X, y = dataset[3]

print(X)
print(y)

tensor([0.0000, 0.4345, 0.1250, 0.0000, 0.1036, 1.0000, 0.0000, 0.0000, 0.0000,
        1.0000])
tensor([0., 1.])


In [8]:
loader = DataLoader(dataset, batch_size = 5, shuffle = True)
for batch_x, batch_y in loader:
  print(batch_x.shape)
  print(batch_y.shape)
  break

torch.Size([5, 10])
torch.Size([5, 2])


In [3]:
class TitanicNeuralNetwork(nn.Module):
    def __init__(self, input_size, output_size):
        super().__init__()
        self.input_size = input_size
        self.output_size = output_size

        self.relu = nn.ReLU()

        self.input_to_hidden = nn.Linear(self.input_size, 5)

        self.hidden_to_output = nn.Linear(5, self.output_size)

    def forward(self, x):
        x = self.input_to_hidden.forward(x)
        x = self.relu.forward(x)
        x = self.hidden_to_output.forward(x)
        x = self.relu.forward(x)

        return x

titanic_nn = TitanicNeuralNetwork(10, 2)
print(titanic_nn)

TitanicNeuralNetwork(
  (relu): ReLU()
  (input_to_hidden): Linear(in_features=10, out_features=5, bias=True)
  (hidden_to_output): Linear(in_features=5, out_features=2, bias=True)
)


In [5]:
random_tensor = torch.rand(3, 10)

titanic_nn.forward(random_tensor)

tensor([[0.0000, 0.0021],
        [0.0000, 0.0021],
        [0.0000, 0.0036]], grad_fn=<ReluBackward0>)